<a href="https://colab.research.google.com/github/midanaca/MiniProjeto_MidanaCa_T8/blob/main/MiniProjeto_MidanaCa_T8_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Título Midana Cá turma T8 26/10/2026


A base usada nesta análise foi baixada no dia 25/10/2026 no seguinte link:

"https://www.kaggle.com/datasets/namespaiva/base-varejo"

In [7]:
from google.colab import files
uploaded = files.upload()

Saving base_varejo.csv to base_varejo.csv

## SPRINT 1 — LEITURA E DIAGNÓSTICO

In [64]:
# Leitura do arquivo importado
import pandas as pd

df = pd.read_csv("base_varejo.csv")

df_original = df.copy()

display(df.head())

  DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0  01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1  01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2  01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3  01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4  01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...

In [65]:
# Quantidade de linhas e colunas
print("Quantidade de linhas: ", df.shape[0])
print("quantidade de colunas: ", df.shape[1])

Quantidade de linhas:  830000
quantidade de colunas:  1

## A tabela está totalmente desorganizada por apresentar apenas uma coluna

Agora vamos separar as colunas

In [66]:
df = pd.read_csv("base_varejo.csv", sep=';')
display(df.head())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

# Traduzir as colunas para facilitar a interpretação

In [67]:
# 1. Criar um dicionário para traduzir os nomes
traducao_colunas = {
    "DATA": "Data",
    "CO_ID": "Compra_id",
    "CL_ID": "Cliente_id",
    "CL_GENERO": "Genero_cliente",
    "CL_EC": "Estado_civil_cliente",
    "CL_FHL": "Filho_cliente",
    "CL_SEG": "Segmento_cliente",
    "PR_ID": "Produto_id",
    "PR_CAT": "Categoria_produto",
    "PR_NOME": "Nome_produto"
}

# 2. Renomear as colunas
df = df.rename(columns=traducao_colunas)

# 3. Exibir os novos nomes
print("\nNomes traduzidos:")
print(df.columns.tolist())

Nomes traduzidos:
['Data', 'Compra_id', 'Cliente_id', 'Genero_cliente', 'Estado_civil_cliente', 'Filho_cliente', 'Segmento_cliente', 'Produto_id', 'Categoria_produto', 'Nome_produto', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [68]:
# Visualizar as primeiras linhas da base
display(df.head())

,Data,Compra_id,Cliente_id,Genero_cliente,Estado_civil_cliente,Filho_cliente,Segmento_cliente,Produto_id,Categoria_produto,Nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [69]:
# Tipos e quantidade de valores preenchidos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Data                  830000 non-null  object
 1   Compra_id             830000 non-null  int64
 2   Cliente_id            830000 non-null  int64
 3   Genero_cliente        830000 non-null  object
 4   Estado_civil_cliente  830000 non-null  int64
 5   Filho_cliente         830000 non-null  int64
 6   Segmento_cliente      830000 non-null  object
 7   Produto_id            830000 non-null  int64
 8   Categoria_produto     830000 non-null  object
 9   Nome_produto          830000 non-null  object
 10  Unnamed: 10           0 non-null       float64
 11  Unnamed: 11           0 non-null       float64
 12  Unnamed: 12           0 non-null       float64
 13  Unnamed: 13           0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [70]:
# Olhar as colunas de 10 a 13 se são 100% vazias
df[['Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13']].isna().all()

Unnamed: 10    True
Unnamed: 11    True
Unnamed: 12    True
Unnamed: 13    True
dtype: bool

## 2-	Qualidade dos dados (Sprint 2)

In [71]:
# Conte quantos valores ausentes existem por coluna
ausentes = df.isna().sum()
display(ausentes)

Data                         0
Compra_id                    0
Cliente_id                   0
Genero_cliente               0
Estado_civil_cliente         0
Filho_cliente                0
Segmento_cliente             0
Produto_id                   0
Categoria_produto            0
Nome_produto                 0
Unnamed: 10             830000
Unnamed: 11             830000
Unnamed: 12             830000
Unnamed: 13             830000
dtype: int64

# Linhas duplicadas

In [72]:
print(
    "Repetições completas além da primeira ocorrência: ",
    df.duplicated().sum() # marca as repetições da primeira ocorrência
)

print(
    "Linhas que participam de grupos repetidos: ",
    df.duplicated(keep=False).sum() # marca todas as ocorrências dos registros repetidos
)

print(
    "Identificadores de pedidos distintos: ",
    df["Compra_id"].nunique()
)

Repetições completas além da primeira ocorrência:  96553
Linhas que participam de grupos repetidos:  184330
Identificadores de pedidos distintos:  18471

In [73]:
# Visualize as linhas duplicadas
display(
    df.loc[df.duplicated(keep=False)])

,Data,Compra_id,Cliente_id,Genero_cliente,Estado_civil_cliente,Filho_cliente,Segmento_cliente,Produto_id,Categoria_produto,Nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE,NaN,NaN,NaN,NaN
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN

In [74]:
# verificar os espaços

colunas_texto = [
    "Genero_cliente",
    "Segmento_cliente",
    "Categoria_produto",
    "Nome_produto"

]

for coluna in colunas_texto:
  quantidade_em_branco = (
      df[coluna]
      .astype("string")
      .str.strip()
      .eq("")
      .sum()
  )

  print(coluna, ":", quantidade_em_branco)

Genero_cliente : 0
Segmento_cliente : 0
Categoria_produto : 0
Nome_produto : 0

## ETAPA 5 — Inconsistências de texto - Investigação de categorias, canais e status

In [75]:
display(
    df["Genero_cliente"].value_counts(dropna=False)
)

Genero_cliente
F    432576
M    397424
Name: count, dtype: int64

In [76]:
display(
    df["Segmento_cliente"].value_counts(dropna=False)
)

Segmento_cliente
B    530163
C    232101
A     67736
Name: count, dtype: int64

In [77]:
display(
    df["Categoria_produto"].value_counts(dropna=False)
)

Categoria_produto
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

In [78]:
display(
    df["Nome_produto"].value_counts(dropna=False)
)

Nome_produto
PRESUNTO COZIDO          14381
SARDINHA                  7490
GEL                       7399
BANANA                    7385
DESENGORDURANTE           7378
                         ...
#N/D                      3650
ABSORVENTE                3639
ALCOOL                    3611
ALIMENTO PARA PASSARO     3605
ALHO                      3574
Name: count, Length: 118, dtype: int64

RESUMO DO QUE FOI ENCONTRADO E DO QUE SERÁ FEITO

1. Quantas linhas e colunas existem?

A base possui 830.000 linhas e 14 colunas.

2. O que cada registro representa?

Cada registro contém informações sobre a data da compra, o gênero e o estado civil do cliente, além da categoria, do segmento e do nome do produto. Em alguns registros, a categoria e o nome do produto aparecem identificados como “#N/D”.

3. Quais informações estão ausentes?

O diagnóstico realizado com o método isna() não identificou valores ausentes reconhecidos por essa verificação.

4. Existem informações duplicadas?

Foram identificadas 96.553 linhas integralmente duplicadas.

5. Existem textos preenchidos apenas com espaços?

Não. Todas as colunas de texto analisadas apresentaram zero registros preenchidos apenas com espaços vazios ("").

6. Quais diferenças de escrita foram encontradas?

Nas quatro colunas analisadas — Genero_cliente, Segmento_cliente, Categoria_produto e Nome_produto —, não foram identificadas diferenças de escrita relacionadas às formas de apresentação das letras maiúsculas e minúsculas.

7. Quais decisões ainda precisam ser tomadas?

É necessário decidir quais repetições devem ser removidas, como padronizar os textos e quais registros devem ser considerados nas análises.

Problema escolhido: registros duplicados e colunas vazias.

Problema encontrado: além das repetições e das colunas vazias, existem 3.650 registros sem identificação da categoria e do nome do produto, apresentados como “#N/D”.

Como isso afeta a análise?

As repetições podem aumentar indevidamente a contagem de registros e, caso sejam utilizadas variáveis financeiras, podem inflar as somas dos valores de compra, produzindo resultados superiores aos reais. Da mesma forma, a ausência de informações sobre as categorias e os nomes dos produtos limita a análise e a classificação adequada dos itens.

Decisão de tratamento proposta: após confirmar que as repetições são indevidas, deve-se manter apenas uma ocorrência de cada registro duplicado e remover as 96.553 cópias excedentes. No entanto, essa operação reduziria a base de 830.000 para 733.447 linhas, e não para 18.471, pois 18.471 corresponde ao número de pedidos distintos, e não ao total de linhas após a remoção das duplicações.

## SPRINT 2 — LIMPEZA E PADRONIZAÇÃO

Não padronizamos os textos, porque como não apresenta nenhuma diferença da escrita dos textos, por isso resolve-se deixar o texto do jeito que está.

In [79]:
# Linhas que repitiram

display(
  df[df.duplicated(keep=False)]
)

,Data,Compra_id,Cliente_id,Genero_cliente,Estado_civil_cliente,Filho_cliente,Segmento_cliente,Produto_id,Categoria_produto,Nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE,NaN,NaN,NaN,NaN
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN

In [80]:
df = df.drop_duplicates().copy()

In [81]:
print("Linhas antes: ", len(df))
print("Linhas depois: ", len(df))

print(
    "Duplicatas restantes: ",
    df.duplicated().sum()
)
display(df.isna().sum())

Linhas antes:  733447
Linhas depois:  733447
Duplicatas restantes:  0

Data                         0
Compra_id                    0
Cliente_id                   0
Genero_cliente               0
Estado_civil_cliente         0
Filho_cliente                0
Segmento_cliente             0
Produto_id                   0
Categoria_produto            0
Nome_produto                 0
Unnamed: 10             733447
Unnamed: 11             733447
Unnamed: 12             733447
Unnamed: 13             733447
dtype: int64

In [82]:
# Eliminar as colunas vazias

df = df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"])

In [27]:
display(df.head())

,Data,Compra_id,Cliente_id,Genero_cliente,Estado_civil_cliente,Filho_cliente,Segmento_cliente,Produto_id,Categoria_produto,Nome_produto
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

## SPRINT 3 — FUNÇÕES

In [83]:
def resumo_numerico(serie):
  return {
      "contagem_valida": serie.count(),
      "media": serie.mean(),
      "minimo": serie.min(),
      "maximo": serie.max()
  }

In [84]:
resumo = resumo_numerico(df["Filho_cliente"])

print("Valores válidos: ", resumo["contagem_valida"])
print("Média: ", round(resumo["media"], 2))
# Acessando com as chaves acentuadas conforme gerado pela função
print("Mínimo: ", resumo.get("minimo", resumo.get("mínimo")))
print("Máximo: ", resumo.get("maximo", resumo.get("máximo")))

Valores válidos:  733447
Média:  1.15
Mínimo:  0
Máximo:  4

In [85]:
df.describe()

,Compra_id,Cliente_id,Estado_civil_cliente,Filho_cliente,Produto_id
count,733447.000000,733447.000000,733447.000000,733447.000000,733447.000000
mean,459941.034680,499.643996,2.597385,1.146049,115.037337
std,265431.394822,287.561653,1.170130,1.416917,66.124263
min,1000.000000,1.000000,1.000000,0.000000,1.000000
25%,232895.000000,254.000000,2.000000,0.000000,58.000000
50%,456422.000000,498.000000,3.000000,0.000000,115.000000
75%,690100.000000,746.000000,4.000000,2.000000,172.000000
max,919822.000000,1000.000000,5.000000,4.000000,229.000000

## SPRINT 4 — ANÁLISE

Filtrar Compra de clientes igual a 4 filhos

In [86]:
filhos_igual_4 = df[df["Filho_cliente"] == 4]

display(filhos_igual_4)

print(
    "Quantidade de registros: ",
    len(filhos_igual_4)
)

,Data,Compra_id,Cliente_id,Genero_cliente,Estado_civil_cliente,Filho_cliente,Segmento_cliente,Produto_id,Categoria_produto,Nome_produto
494,01/02/2019,1298,406,M,2,4,C,72,HIGIENE,CONDICIONADOR
495,01/02/2019,1298,406,M,2,4,C,139,LIMPEZA,REMOVEDOR
496,01/02/2019,1298,406,M,2,4,C,119,PET,RACAO UMIDA PARA GATOS
497,01/02/2019,1298,406,M,2,4,C,137,ALIMENTOS,REQUEIJAO
498,01/02/2019,1298,406,M,2,4,C,76,HIGIENE,FIO DENTAL
...,...,...,...,...,...,...,...,...,...,...
829856,19/08/2022,919716,801,M,1,4,B,158,HIGIENE,PAPEL HIGIENICO
829857,19/08/2022,919716,801,M,1,4,B,37,ALIMENTOS,LEITE
829859,19/08/2022,919716,801,M,1,4,B,64,ALIMENTOS,UVA
829860,19/08/2022,919716,801,M,1,4,B,116,PET,RACAO SECA PARA CAES
829862,19/08/2022,919716,801,M,1,4,B,157,ALIMENTOS,PAPINHA INFANTIL

Quantidade de registros:  71041

In [87]:
# Percentual de registros acima de R$ 500

percentual = (
    len(filhos_igual_4)
    / df["Filho_cliente"].count() * 100
)

print(round(percentual, 2))

9.69

Usamos 733.447 para calcular o percentual entre os registros dos clientes cujo número dos filhos é igual a 4.

##	Filtros e agrupamentos

Vamos fazer a contagem de registros por categoria e soma dos valores por gênero

In [88]:
# Agrupar a coluna categoria de produtos.

produto_por_categoria = (
    df.groupby("Categoria_produto")
    .size()
    .sort_values(ascending=False)
)
display(produto_por_categoria)

Categoria_produto
ALIMENTOS     384197
HIGIENE       137702
LIMPEZA       128632
BEBIDAS        38264
PET            28553
ACESSORIOS     12871
#N/D            3228
dtype: int64

Alimentos é a categoria dos produtos mais frequente nesta base, aparecendo em 7 categorias registradas nesta base analisada.

In [89]:
# Agrupar por gênero do cliente
grupos_genero_cliente = df.groupby(
    "Genero_cliente", dropna=False
)["Filho_cliente"]

# Criar resumo por gênero
resumo_por_genero = pd.DataFrame({
    "registros": grupos_genero_cliente.size(),
    "valores_validos": grupos_genero_cliente.count(),
    "soma_valores_conhecidos": grupos_genero_cliente.sum(min_count=1)
})

display(resumo_por_genero)

                registros  valores_validos  soma_valores_conhecidos
Genero_cliente
F                  382427           382427                   416678
M                  351020           351020                   423888

## SPRINT 5 — EXPORTAÇÃO E CONCLUSÕES

In [92]:
df.to_csv(
    "varejo_limpo.csv",
    index=False
)

In [93]:
conferencia = pd.read_csv(
    "varejo_limpo.csv"
)

print(conferencia.shape)
print(conferencia.columns.tolist())

(733447, 10)
['Data', 'Compra_id', 'Cliente_id', 'Genero_cliente', 'Estado_civil_cliente', 'Filho_cliente', 'Segmento_cliente', 'Produto_id', 'Categoria_produto', 'Nome_produto']

Interpretação final
1. Uma estatística com sua unidade

   A média do número de filhos dos clientes, considerando os 733.447 registros, é de 1,15 filho por registro.

2. Uma interpretação com filtro

   Existem 71.041 registros em que o número de filhos do cliente é igual a 4.

3. Uma interpretação do primeiro agrupamento

   A categoria Alimentos é a que apresenta o maior número de registros, totalizando 384.197.

4. Uma interpretação do segundo agrupamento, com mais informações

   Os valores conhecidos do número de filhos dos clientes do gênero feminino somam 416.678.

5. Uma limitação da análise

   A base não possui uma coluna com dados numéricos decimais, como, por exemplo, o valor da compra dos produtos.

6. Uma recomendação sugerida

   Recomenda-se incluir na base os valores de compra de cada produto, a fim de permitir o cálculo do valor total das compras por gênero e/ou por segmento de cliente.