<a href="https://colab.research.google.com/github/midanaca/MiniProjeto_MidanaCa_T8/blob/main/MiniProjeto_MidanaCa_T8_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Título Midana Cá turma T8 26/10/2026


A base usada nesta análise foi baixada no dia 25/10/2026 no seguinte link:

"https://www.kaggle.com/datasets/namespaiva/base-varejo"

## 1-	Importação e diagnóstico da estrutura (Sprint 1)

In [1]:
from google.colab import files
uploaded = files.upload()

Saving base_varejo.csv to base_varejo.csv

In [47]:
# Leitura do arquivo importado
import pandas as pd

df = pd.read_csv("base_varejo.csv")

df_original = df.copy()

display(df.head())

  DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0  01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1  01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2  01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3  01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4  01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...

In [49]:
# Quantidade de linhas e colunas
print("Quantidade de linhas: ", df.shape[0])
print("quantidade de colunas: ", df.shape[1])

Quantidade de linhas:  830000
quantidade de colunas:  1

## A tabela está totalmente desorganizada por apresentar apenas uma coluna

Agora vamos separar as colunas

In [50]:
df = pd.read_csv("base_varejo.csv", sep=';')
display(df.head())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

# Traduzir as colunas para facilitar a interpretação

In [55]:
# 1. Criar um dicionário para traduzir os nomes
traducao_colunas = {
    "DATA": "Data",
    "CO_ID": "Compra_id",
    "CL_ID": "Cliente_id",
    "CL_GENERO": "Genero_cliente",
    "CL_EC": "Estado_civil_cliente",
    "CL_FHL": "Filho_cliente",
    "CL_SEG": "Segmento_cliente",
    "PR_ID": "Produto_id",
    "PR_CAT": "Categoria_produto",
    "PR_NOME": "Nome_produto"
}

# 2. Renomear as colunas
df = df.rename(columns=traducao_colunas)

# 3. Exibir os novos nomes
print("\nNomes traduzidos:")
print(df.columns.tolist())

Nomes traduzidos:
['Data', 'Compra_id', 'Cliente_id', 'Genero_cliente', 'Estado_civil_cliente', 'Filho_cliente', 'Segmento_cliente', 'Produto_id', 'Categoria_produto', 'Nome_produto', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [56]:
# Visualizar as primeiras linhas da base
display(df.head())

,Data,Compra_id,Cliente_id,Genero_cliente,Estado_civil_cliente,Filho_cliente,Segmento_cliente,Produto_id,Categoria_produto,Nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [57]:
# Tipos e quantidade de valores preenchidos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Data                  830000 non-null  object
 1   Compra_id             830000 non-null  int64
 2   Cliente_id            830000 non-null  int64
 3   Genero_cliente        830000 non-null  object
 4   Estado_civil_cliente  830000 non-null  int64
 5   Filho_cliente         830000 non-null  int64
 6   Segmento_cliente      830000 non-null  object
 7   Produto_id            830000 non-null  int64
 8   Categoria_produto     830000 non-null  object
 9   Nome_produto          830000 non-null  object
 10  Unnamed: 10           0 non-null       float64
 11  Unnamed: 11           0 non-null       float64
 12  Unnamed: 12           0 non-null       float64
 13  Unnamed: 13           0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [58]:
# Olhar as colunas de 10 a 13 se são 100% vazias
df[['Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13']].isna().all()

Unnamed: 10    True
Unnamed: 11    True
Unnamed: 12    True
Unnamed: 13    True
dtype: bool

## 2-	Qualidade dos dados (Sprint 2)

In [59]:
# Conte quantos valores ausentes existem por coluna
ausentes = df.isna().sum()
display(ausentes)

Data                         0
Compra_id                    0
Cliente_id                   0
Genero_cliente               0
Estado_civil_cliente         0
Filho_cliente                0
Segmento_cliente             0
Produto_id                   0
Categoria_produto            0
Nome_produto                 0
Unnamed: 10             830000
Unnamed: 11             830000
Unnamed: 12             830000
Unnamed: 13             830000
dtype: int64

# Linhas duplicadas

In [63]:
print(
    "Repetições completas além da primeira ocorrência: ",
    df.duplicated().sum() # marca as repetições da primeira ocorrência
)

print(
    "Linhas que participam de grupos repetidos: ",
    df.duplicated(keep=False).sum() # marca todas as ocorrências dos registros repetidos
)

print(
    "Identificadores de pedidos distintos: ",
    df["Compra_id"].nunique()
)

Repetições completas além da primeira ocorrência:  96553
Linhas que participam de grupos repetidos:  184330
Identificadores de pedidos distintos:  18471

In [67]:
# Visualize as linhas duplicadas
display(
    df.loc[df.duplicated(keep=False)])

,Data,Compra_id,Cliente_id,Genero_cliente,Estado_civil_cliente,Filho_cliente,Segmento_cliente,Produto_id,Categoria_produto,Nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE,NaN,NaN,NaN,NaN
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN

In [81]:
# verificar os espaços

colunas_texto = [
    "Genero_cliente",
    "Segmento_cliente",
    "Categoria_produto",
    "Nome_produto"

]

for coluna in colunas_texto:
  quantidade_em_branco = (
      df[coluna]
      .astype("string")
      .str.strip()
      .eq("")
      .sum()
  )

  print(coluna, ":", quantidade_em_branco)

Genero_cliente : 0
Segmento_cliente : 0
Categoria_produto : 0
Nome_produto : 0

## ETAPA 5 — Inconsistências de texto - Investigação de categorias, canais e status

In [71]:
display(
    df["Genero_cliente"].value_counts(dropna=False)
)

Genero_cliente
F    432576
M    397424
Name: count, dtype: int64

In [72]:
display(
    df["Segmento_cliente"].value_counts(dropna=False)
)

Segmento_cliente
B    530163
C    232101
A     67736
Name: count, dtype: int64

In [73]:
display(
    df["Categoria_produto"].value_counts(dropna=False)
)

Categoria_produto
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

In [80]:
display(
    df["Nome_produto"].value_counts(dropna=False)
)

Nome_produto
PRESUNTO COZIDO          14381
SARDINHA                  7490
GEL                       7399
BANANA                    7385
DESENGORDURANTE           7378
                         ...
#N/D                      3650
ABSORVENTE                3639
ALCOOL                    3611
ALIMENTO PARA PASSARO     3605
ALHO                      3574
Name: count, Length: 118, dtype: int64

RESUMO DO QUE FOI ENCONTRADO E O QUE VAI SER VAI SER FEITO.

1.	Quantas linhas e colunas existem?

A base possui 830000 linhas e 14 colunas

•
2.	O que cada registro representa?

Cada registro descreve a informação sobre a data de compra, informações sobre o gênero e estado civil de cliente. Também possui a informação sobre a categoria, o segmento e o nome de produto apresentando desta maneira “#N/D”.
•

3.	Quais informações estão ausentes?

O diagnóstico isna() não apresentam ausências reconhecidas por essa verificação.

4.	Existem as informações duplicadas?

Foram 96.553 compras repetidas
5.	Existem textos preenchidos apenas com espaços?

Não. Todas as colunas de texto apresentaram zero informação inscrita com (“”)

6.	Quais diferenças de escrita foram encontras?

Nas quatro colunas analisadas Genero_cliente, Segmento cliente, Categoria_produto, Nome_produto todas apresentaram uma única forma de escrita com letras maiúsculas.

7.	Quais decisões ainda precisam ser identificadas?

Quais repetições remover;
Como padronizar os textos;
Quais registros consideramos nas análises.
Problema escolhido: pedidos repetidos e as colunas vazias
Problema encontrado: Também existem categorias e nome de produtos que não foram preenchidos totalizando 3.650 compras sem preenchimento de categoria e nome de produto.

Como afeta a análise: as repetições elas podem aumentar indevidamente a contagem de pedidos, e a soma de valores de compra, produzindo resultados superiores aos registrados sem essas cópias.
Decisão de tratamento proposta: após confirmar que são repetições indevidas, manter UMA ocorrência de cada pedido e remover 96.553 cópias excedentes. Somente essa operação reduziria a base de 830.000 para 18.471 linhas.