<a href="https://colab.research.google.com/github/midanaca/MiniProjeto_MidanaCa_T8/blob/main/MiniProjeto_MidanaCa_T8_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Título Midana Cá turma T8 26/10/2026


A base usada nesta análise foi baixada no dia 25/10/2026 no seguinte link:

"https://www.kaggle.com/datasets/namespaiva/base-varejo"

## 1-	Importação e diagnóstico da estrutura (Sprint 1)

In [1]:
from google.colab import files
uploaded = files.upload()

Saving base_varejo.csv to base_varejo.csv

In [2]:
# Leitura do arquivo importado
import pandas as pd

df = pd.read_csv("base_varejo.csv")

df_original = df.copy()

display(df.head())

  DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0  01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1  01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2  01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3  01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4  01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...

In [3]:
# Quantidade de linhas e colunas
print("Quantidade de linhas: ", df.shape[0])
print("quantidade de colunas: ", df.shape[1])

Quantidade de linhas:  830000
quantidade de colunas:  1

## A tabela está totalmente desorganizada por apresentar apenas uma coluna

Agora vamos separar as colunas

In [4]:
df = pd.read_csv("base_varejo.csv", sep=';')
display(df.head())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [5]:
# Nomes das colunas
print(df.columns.tolist())

['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [7]:
# Tipos e quantidade de valores preenchidos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [6]:
# Olhar as colunas de 10 a 13 se são 100% vazias
df[['Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13']].isna().all()

Unnamed: 10    True
Unnamed: 11    True
Unnamed: 12    True
Unnamed: 13    True
dtype: bool

## 2-	Qualidade dos dados (Sprint 2)

In [7]:
# Conte quantos valores ausentes existem por coluna
ausentes = df.isna().sum()
display(ausentes)

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [8]:
# Calcule o percentual de ausentes
percentuais = (
    df.isna().mean() * 100
).round(2)

resumo_ausentes = pd.DataFrame({
    "quantidade": ausentes,
    "percentual": percentuais
})
display(resumo_ausentes)

             quantidade  percentual
DATA                  0         0.0
CO_ID                 0         0.0
CL_ID                 0         0.0
CL_GENERO             0         0.0
CL_EC                 0         0.0
CL_FHL                0         0.0
CL_SEG                0         0.0
PR_ID                 0         0.0
PR_CAT                0         0.0
PR_NOME               0         0.0
Unnamed: 10      830000       100.0
Unnamed: 11      830000       100.0
Unnamed: 12      830000       100.0
Unnamed: 13      830000       100.0